---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2572322785-dR9eQrUobv1lHPC9vHOmSDqBLmLAWCOlGw0ee7Y
:access_token_secret: kXFKg3HsK8Xlgcq6sKDty25yJH6IXfuqoaBZaqsBa98Mj
